USE Simplon;
DROP TABLE IF EXISTS stock_etab;
CREATE TABLE stock_etab (
siren VARCHAR(9) COMMENT "Numéro Siren"	,
nic VARCHAR(5) COMMENT "Numéro interne de classement de l'établissement",
siret VARCHAR(14) COMMENT "Numéro Siret" ,
statutDiffusionEtablissement VARCHAR(1) COMMENT "Statut de diffusion de l’établissement",
dateCreationEtablissement	 DATETIME COMMENT "Date de création de l’établissement"	,
trancheEffectifsEtablissement  VARCHAR(2) COMMENT "Tranche d’effectif salarié de l’établissement"	,
anneeEffectifsEtablissement	DATETIME	COMMENT "Année de validité de la tranche d’effectif salarié de l’établissement",
activitePrincipaleRegistreMetiersEtablissement VARCHAR(6) COMMENT	"Activité exercée par l’artisan inscrit au registre des métiers"	,
dateDernierTraitementEtablissement	DATETIME COMMENT "Date du dernier traitement de l’établissement dans le répertoire Sirene",
etablissementSiege	 VARCHAR(5) COMMENT "Qualité de siège ou non de l’établissement",
nombrePeriodesEtablissement  VARCHAR(2) COMMENT "Nombre de périodes de l’établissement",
complementAdresseEtablissement 	VARCHAR(38)	COMMENT "Complément d’adresse",
numeroVoieEtablissement 	VARCHAR(4)	COMMENT "Numéro de voie",
indiceRepetitionEtablissement 	VARCHAR(1) COMMENT "Indice de répétition dans la voie",
typeVoieEtablissement	VARCHAR(4) COMMENT "Type de voie",
libelleVoieEtablissement	VARCHAR(100)	COMMENT "Libellé de voie",
codePostalEtablissement VARCHAR(5) COMMENT "Code postal"	,
libelleCommuneEtablissement	VARCHAR(100)	COMMENT "Libellé de la commune",
libelleCommuneEtrangerEtablissement	VARCHAR(100)	COMMENT "Libellé de la commune pour un établissement situé à l’étranger",
distributionSpecialeEtablissement	VARCHAR(26)	COMMENT "Distribution spéciale de l’établissement",
codeCommuneEtablissement	VARCHAR(5) COMMENT	"Code commune de l’établissement",
codeCedexEtablissement	VARCHAR(9)	COMMENT "Code cedex",
libelleCedexEtablissement	VARCHAR(100)	COMMENT "Libellé du code cedex",
codePaysEtrangerEtablissement	VARCHAR(5)  COMMENT "Code pays pour un établissement situé à l’étranger",
libellePaysEtrangerEtablissement	VARCHAR(100) COMMENT "Libellé du pays pour un établissement situé à l’étranger",
complementAdresse2Etablissement	VARCHAR(38)	COMMENT "Complément d’adresse secondaire",
numeroVoie2Etablissement	VARCHAR(4)	COMMENT "Numéro de la voie de l’adresse secondaire",
indiceRepetition2Etablissement	VARCHAR(1)	COMMENT "Indice de répétition dans la voie pour l’adresse secondaire",
typeVoie2Etablissement	VARCHAR(4)	COMMENT "Type de voie de l’adresse secondaire",
libelleVoie2Etablissement	VARCHAR(100)	COMMENT "Libellé de voie de l’adresse secondaire",
codePostal2Etablissement	VARCHAR(5)	COMMENT "Code postal de l’adresse secondaire",
libelleCommune2Etablissement	VARCHAR(100)	COMMENT "Libellé de la commune de l’adresse secondaire",
libelleCommuneEtranger2Etablissement	VARCHAR(100)	COMMENT "Libellé de la commune de l’adresse secondaire pour un établissement situé à l’étranger",
distributionSpeciale2Etablissement 	VARCHAR(26) COMMENT	"Distribution spéciale de l’adresse secondaire de l’établissement",
codeCommune2Etablissement		VARCHAR(5) COMMENT "Code commune de l’adresse secondaire",
codeCedex2Etablissement	VARCHAR(9)	COMMENT "Code cedex de l’adresse secondaire",
libelleCedex2Etablissement	VARCHAR(100)	COMMENT "Libellé du code cedex de l’adresse secondaire",
codePaysEtranger2Etablissement 	VARCHAR(5)	COMMENT "Code pays de l’adresse secondaire pour un établissement situé à l’étranger",
libellePaysEtranger2Etablissement 	VARCHAR(100) COMMENT	"Libellé du pays de l’adresse secondaire pour un établissement situé à l’étranger",
dateDebut	DATETIME COMMENT "Date de début d'une période d'historique d'un établissement",
etatAdministratifEtablissement	VARCHAR(1)	COMMENT "État administratif de l’établissement",
enseigne1Etablissement		VARCHAR(50) COMMENT "Première ligne d’enseigne de l’établissement",
enseigne2Etablissement		VARCHAR(50) COMMENT "Deuxième ligne d’enseigne de l’établissement",
enseigne3Etablissement	VARCHAR(50)	COMMENT "Troisième ligne d’enseigne de l’établissement",
denominationUsuelleEtablissement	VARCHAR(100)	COMMENT "Dénomination usuelle de l’établissement",
activitePrincipaleEtablissement	VARCHAR(6)	COMMENT "Activité principale de l'établissement pendant la période",
nomenclatureActivitePrincipaleEtablissement 	VARCHAR(8)	COMMENT "Nomenclature d’activité de la variable activitePrincipaleEtablissement",
caractereEmployeurEtablissement VARCHAR(1)	COMMENT "Caractère employeur de l’établissement"	
);

DROP TABLE IF EXISTS stock_etab_hist;
CREATE TABLE stock_etab_hist (
siren VARCHAR(9) COMMENT "Numéro Siren",
nic VARCHAR(5) COMMENT	"Numéro interne de classement de l'établissement",
siret	VARCHAR(14) COMMENT "Numéro Siret",
dateFiN DATETIME COMMENT "Date de fin d'une période d'historique d'un établissement",
dateDebut	DATETIME COMMENT "Date de début d'une période d'historique d'un établissement",
etatAdministratifEtablissement	VARCHAR(1) COMMENT "État administratif de l’établissement,",
changementEtatAdministratifEtablissement	VARCHAR(5) COMMENT "Indicatrice de changement de l’état administratif de l’établissement",
enseigne1Etablissement	VARCHAR(50) COMMENT "Première ligne d’enseigne de l’établissement",
enseigne2Etablissement VARCHAR(50)	COMMENT "Deuxième ligne d’enseigne de l’établissement",
enseigne3Etablissement VARCHAR(50) COMMENT	"Troisième ligne d’enseigne de l’établissement",
changementEnseigneEtablissement VARCHAR(5) COMMENT	"Indicatrice de changement de l’enseigne de l’établissement",
denominationUsuelleEtablissement VARCHAR(100) COMMENT	"Dénomination usuelle de l’établissement",
changementDenominationUsuelleEtablissement	VARCHAR(5) COMMENT "Indicatrice de changement de la dénomination usuelle de l’unité légale",
activitePrincipaleEtablissement	VARCHAR(6) COMMENT "Activité principale de l'établissement pendant la période",
nomenclatureActivitePrincipaleEtablissement VARCHAR(8) COMMENT	"Nomenclature d’activité de la variable activitePrincipaleEtablissement",
changementActivitePrincipaleEtablissement	VARCHAR(5) COMMENT "Indicatrice de changement de l’activité principale de l’établissement",	
caractereEmployeurEtablissement	VARCHAR(1) COMMENT "Caractère employeur de l’établissement",
changementCaractereEmployeurEtablissement VARCHAR(5) COMMENT"Indicatrice de changement du caractère employeur de l’établissement"
);